# Generated by Django 2.2.13 on 2020-11-27 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_name',
            field=models.TextField(default='Null', max_length=150, verbose_name='Account Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='account_number',
            field=models.TextField(default='Null', max_length=150, verbose_name='Account Number'),
        ),
    ]
