# Generated by Django 2.2.13 on 2020-11-27 05:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0002_auto_20201127_0151'),
    ]

    operations = [
        migrations.CreateModel(
            name='HubLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.EmailField(max_length=90, unique=True, verbose_name='Longitude')),
                ('latitute', models.TextField(max_length=200, verbose_name='Latitute')),
                ('hub_address', models.TextField(max_length=200, verbose_name='Address')),
                ('hub_state', models.TextField(max_length=200, verbose_name='State')),
                ('hub_council_area', models.TextField(max_length=200, verbose_name='LGA/Council Area')),
                ('hub_country', models.TextField(max_length=200, verbose_name='Country')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'hub_locations',
            },
        ),
    ]
