# Generated by Django 2.2.13 on 2020-11-27 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0003_hublocation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hublocation',
            name='longitude',
        ),
        migrations.AddField(
            model_name='hublocation',
            name='longi',
            field=models.TextField(default=654433, max_length=90, unique=True, verbose_name='Longitude'),
            preserve_default=False,
        ),
    ]
