# Generated by Django 2.2.13 on 2020-11-27 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0004_auto_20201127_0649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hublocation',
            name='longi',
        ),
        migrations.AddField(
            model_name='hublocation',
            name='longitude',
            field=models.TextField(default=4564, max_length=90, verbose_name='Longitude'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hublocation',
            name='latitute',
            field=models.TextField(max_length=90, verbose_name='Latitute'),
        ),
    ]
