# Generated by Django 2.2.13 on 2020-11-27 11:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0005_auto_20201127_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='hublocation',
            name='hub_name',
            field=models.TextField(default=django.utils.timezone.now, max_length=20, verbose_name='Hub Name'),
            preserve_default=False,
        ),
    ]
