# Generated by Django 2.2.13 on 2020-11-29 13:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0006_hublocation_hub_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailCollector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=90, unique=True, verbose_name='Email')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'Potential_Users_email',
            },
        ),
        migrations.AlterField(
            model_name='hublocation',
            name='hub_name',
            field=models.TextField(max_length=100, verbose_name='Hub Name'),
        ),
    ]
