# Generated by Django 2.2.13 on 2020-11-30 12:31

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0008_recycleditems_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.TextField(max_length=500, verbose_name='Item Manufacturer')),
                ('barcode_identification', models.TextField(max_length=500, verbose_name='Item Barcode Identification')),
                ('amount', models.FloatField(default=0, verbose_name='Coins Worth')),
                ('date_added_with_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_added', models.DateField(default=datetime.date.today)),
            ],
            options={
                'db_table': 'Manufacturer_table',
            },
        ),
    ]
