# Generated by Django 3.1.2 on 2020-12-26 00:48

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0011_brandcollector_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.TextField(default='Admin', max_length=500, verbose_name='Sender')),
                ('message', models.TextField(default='hello admin!', max_length=500, verbose_name='Feedback Message')),
                ('date_added_with_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_added', models.DateField(default=datetime.date.today)),
            ],
            options={
                'db_table': 'Notification_table',
            },
        ),
    ]
