# Generated by Django 3.1.2 on 2021-01-02 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0012_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandcollector',
            name='category',
            field=models.TextField(default='Plastic', max_length=500, verbose_name='Category of Waste'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(default='hello admin!', max_length=500, verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='sender',
            field=models.TextField(default='Admin', max_length=500, verbose_name='Sender Email'),
        ),
    ]
