# Generated by Django 3.1.2 on 2021-01-02 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0013_auto_20210102_2029'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bar', models.CharField(max_length=100)),
            ],
        ),
    ]
