# Generated by Django 3.1.2 on 2021-01-02 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0014_foo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Foo',
        ),
    ]
