# Generated by Django 3.1.2 on 2021-01-02 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0015_delete_foo'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='ratings',
            field=models.TextField(default='Excited', max_length=500, verbose_name='Ratings'),
        ),
    ]
